//NO EXISTE "IN" ENTRE LOS PULSADORES, PORQUE NO SE USA EN MODO PULSADOR LA ENTRADA

// kPin_driverDc(index del kpin, GPIO_RAW)
kPin_driverDc(P0N_MENU,RA0);//P0 INDICA QUE USA EL ELEMENTO 0 DEL ARRAY DE PULSADORES
kPin_driverDc(P1N_SET,RA2);
kPin_driverDc(P0P_MENU,RA0);
kPin_driverDc(P2N_ACCEPT,RE3);
