//NO EXISTE "IN" ENTRE LOS PULSADORES, PORQUE NO SE USA EN MODO PULSADOR LA ENTRADA
puls_dc_driver(P0N_MENU,FLANCO_N,RA0);//P0 INDICA QUE USA EL ELEMENTO 0 DEL ARRAY DE PULSADORES
puls_dc_driver(P1N_SET,FLANCO_N,RA2);
puls_dc_driver(P0P_MENU,FLANCO_P,RA0);
puls_dc_driver(P2N_ACCEPT,FLANCO_N,RE3);
